package org.megadiiiii.elms_api.services.impl;

import org.megadiiiii.elms_api.config.PasswordGenerator;
import org.megadiiiii.elms_api.constant.RoleType;
import org.megadiiiii.elms_api.constant.UserStatus;
import org.megadiiiii.elms_api.dto.request.StaffRequestDTO;
import org.megadiiiii.elms_api.dto.response.StaffDetailDTO;
import org.megadiiiii.elms_api.dto.response.StaffSummaryDTO;
import org.megadiiiii.elms_api.mappers.StaffMapper;
import org.megadiiiii.elms_api.models.Role;
import org.megadiiiii.elms_api.models.StaffProfile;
import org.megadiiiii.elms_api.models.User;
import org.megadiiiii.elms_api.repository.RoleRepository;
import org.megadiiiii.elms_api.repository.StaffRepository;
import org.megadiiiii.elms_api.repository.UserRepository;
import org.megadiiiii.elms_api.services.EmailService;
import org.megadiiiii.elms_api.services.StaffService;
import org.megadiiiii.elms_api.services.AuditLogService;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.security.crypto.password.PasswordEncoder;    
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.util.List;

@Service
@RequiredArgsConstructor
public class StaffServiceImpl implements StaffService {
    private final StaffRepository staffRepository;
    private final PasswordEncoder passwordEncoder;
    private final RoleRepository roleRepository;
    private final UserRepository userRepository;
    private final StaffMapper staffMapper;
    private final PasswordGenerator passwordGenerator;
    private final EmailService emailService;
    private final AuditLogService auditLogService;


    @Override
    public Page<StaffSummaryDTO> getAllStaffSummaries(int page, int size, String keyword, Long roleId) {
        Pageable pageable = PageRequest.of(page - 1, size);
        // Nếu keyword rỗng thì coi như null để Query xử lý
        String searchKeyword = (keyword != null && !keyword.isBlank()) ? keyword : null;
        return staffRepository.searchStaffs(searchKeyword, roleId, pageable);
    }

    @Override
    public StaffDetailDTO getStaffDetailById(Long id) {
        return staffRepository.findStaffDetailById(id)
                .orElseThrow(() -> new IllegalArgumentException("Nhân viên không tồn tại hoặc đã bị xóa!"));
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void createStaff(StaffRequestDTO requestDTO) {
        // 1. Kiểm tra email đã tồn tại chưa
        if (userRepository.findByEmail(requestDTO.getEmail()).isPresent()) {
            throw new IllegalArgumentException("Email '" + requestDTO.getEmail() + "' đã được sử dụng bởi tài khoản khác!");
        }

        String autoGeneratedCode = generateNextStaffCode(requestDTO.getRoleId());
        String rawPassword = passwordGenerator.generateSecurePassword();

        User user = new User();
        user.setUsername(autoGeneratedCode);
        user.setEmail(requestDTO.getEmail());
        user.setPassword(passwordEncoder.encode(rawPassword));

        // --- ĐẨY THÔNG TIN LÊN USER --- [cite: 2026-03-24]
        user.setFullName(requestDTO.getStaffName());
        user.setPhone(requestDTO.getStaffPhone());
        user.setGender(requestDTO.getGender());
        user.setAddress(requestDTO.getAddress());
        user.setDob(requestDTO.getDob());
        user.setAvatar("default-avatar.png");
        user.setNationality(requestDTO.getNationality());

        Role role = roleRepository.findById(requestDTO.getRoleId())
                .orElseThrow(() -> new IllegalArgumentException("Chức vụ (Role) không tồn tại"));
        user.setRole(role);
        user.setStatus(UserStatus.ACTIVE);

        // Profile giờ chỉ giữ staffCode và nationality
        StaffProfile profile = StaffProfile.builder()
                .staffCode(autoGeneratedCode)
                .user(user)
                .build();

        // Xử lý ảnh đại diện (Lưu tên file vào User)
        if (requestDTO.getAvatarUrl() != null && !requestDTO.getAvatarUrl().isBlank()) {
            user.setAvatar(requestDTO.getAvatarUrl());
        }

        user.setStaffProfile(profile);
        staffRepository.save(user); // Cascade sẽ tự lưu profile
        emailService.sendAccountInfo(user.getEmail(), user.getUsername(), rawPassword, role.getName().name());
        
        java.util.Map<String, Object> newMap = new java.util.LinkedHashMap<>();
        newMap.put("fullName", user.getFullName());
        newMap.put("username", user.getUsername());
        newMap.put("email", user.getEmail());
        newMap.put("phone", user.getPhone());
        newMap.put("role", role.getName().name());
        newMap.put("status", user.getStatus().name());

        auditLogService.log("CREATE_STAFF", "tạo tài khoản nhân viên mới: " + user.getFullName() + " (" + user.getUsername() + ") với vai trò " + role.getName().name() + ".", "User", user.getId(), null, newMap);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void updateStaff(Long id, StaffRequestDTO dto) {
        User user = staffRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Không tìm thấy nhân viên!"));
        
        // 1. Kiểm tra email nếu có thay đổi
        if (!user.getEmail().equalsIgnoreCase(dto.getEmail())) {
            userRepository.findByEmail(dto.getEmail()).ifPresent(existingUser -> {
                if (!existingUser.getId().equals(user.getId())) {
                    throw new IllegalArgumentException("Email '" + dto.getEmail() + "' đã được sử dụng bởi tài khoản khác!");
                }
            });
        }

        StaffProfile profile = user.getStaffProfile();

        // Update Role if roleId changed
        if (user.getRole() == null || !user.getRole().getId().equals(dto.getRoleId())) {
            Role role = roleRepository.findById(dto.getRoleId())
                    .orElseThrow(() -> new IllegalArgumentException("Chức vụ (Role) không tồn tại"));
            user.setRole(role);
        }

        java.util.Map<String, Object> oldMap = new java.util.LinkedHashMap<>();
        oldMap.put("fullName", user.getFullName());
        oldMap.put("email", user.getEmail());
        oldMap.put("phone", user.getPhone());
        oldMap.put("role", user.getRole() == null ? "" : user.getRole().getName().name());
        oldMap.put("status", user.getStatus().name());

        // 2. GHIM LẠI ẢNH CŨ TỪ USER
        String currentAvatar = user.getAvatar();

        // 3. Cập nhật User thông qua Mapper
        staffMapper.updateEntityFromDTO(dto, user);

        // 4. Xử lý ảnh mới
        if (dto.getAvatarUrl() != null && !dto.getAvatarUrl().isBlank()) {
            user.setAvatar(dto.getAvatarUrl());
            if (currentAvatar != null && !currentAvatar.equals(dto.getAvatarUrl()) && !currentAvatar.equals("default-avatar.png")) {
                try {
                    Files.deleteIfExists(Paths.get("./uploads/avatars").resolve(currentAvatar));
                } catch (IOException e) {
                    // Bỏ qua lỗi xóa file cũ nếu gặp sự cố
                }
            }
        } else {
            user.setAvatar(currentAvatar); // Giữ ảnh cũ ở User
        }

        staffRepository.save(user);

        java.util.Map<String, Object> newMap = new java.util.LinkedHashMap<>();
        newMap.put("fullName", user.getFullName());
        newMap.put("email", user.getEmail());
        newMap.put("phone", user.getPhone());
        newMap.put("role", user.getRole() == null ? "" : user.getRole().getName().name());
        newMap.put("status", user.getStatus().name());

        auditLogService.log("UPDATE_STAFF", "cập nhật tài khoản nhân viên: " + user.getFullName() + " (" + user.getUsername() + ").", "User", user.getId(), oldMap, newMap);
    }

    @Override
    public StaffRequestDTO getStaffRequestById(Long id) {
        User user = staffRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Không tìm thấy nhân viên!"));

        return staffMapper.toRequestDTO(user);
    }

    @Override
    public String generateNextStaffCode(Long roleId) {
        // 1. Lấy RoleType từ ID (Phải khớp với ID trong DB)
        RoleType role = RoleType.fromID(roleId);
        if (role == null) {
            throw new IllegalArgumentException("Không tìm thấy roleId!");
        }

        // 2. Tạo prefix chuẩn: [PREFIX]-[NĂM] (VD: AD-2026)
        String fullPrefix = role.getPrefix() + "-" + LocalDate.now().getYear();

        // 3. Tìm mã lớn nhất có prefix này trong DB
        String lastCode = staffRepository.findMaxStaffCode(fullPrefix);

        int nextNum = 1;
        if (lastCode != null && lastCode.startsWith(fullPrefix)) {
            try {
                // Cắt chuỗi sau prefix để lấy số thứ tự (ví dụ: lấy "0001" từ "AD-20260001")
                // Độ dài fullPrefix là 7 (AD-2026), substring từ index 7
                String numberPart = lastCode.substring(fullPrefix.length());
                nextNum = Integer.parseInt(numberPart) + 1;
            } catch (Exception e) {
                nextNum = 1; // Có lỗi thì reset về 1 cho lành
            }
        }

        // 4. Trả về format chuẩn 4 chữ số: AD-20260001
        return fullPrefix + String.format("%04d", nextNum);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void resetPassword(Long id) {
        User user = staffRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy nhân viên để reset!"));

        // 1. Tạo mật khẩu mới
        String newRawPassword = passwordGenerator.generateSecurePassword();

        // 2. Mã hóa và lưu vào DB
        user.setPassword(passwordEncoder.encode(newRawPassword));
        staffRepository.save(user);

        // 3. Gửi mail (Dùng lại hàm sendEmail cũ)
        emailService.sendResetPassword(user.getEmail(), user.getUsername(), newRawPassword);
        auditLogService.log("RESET_STAFF_PASSWORD", "thiết lập lại mật khẩu cho nhân viên: " + user.getFullName() + " (" + user.getUsername() + ").");
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public String toggleStaffStatus(Long id) {
        User user = staffRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy thằng nào để xử lý!"));

        String action;
        if (user.getStatus() == UserStatus.ACTIVE) {
            user.setStatus(UserStatus.INACTIVE);
            action = "Khóa"; // Đang Active thì hành động là Khóa [cite: 2026-03-24]
        } else {
            user.setStatus(UserStatus.ACTIVE);
            action = "Mở khóa"; // Ngược lại là Mở khóa [cite: 2026-03-24]
        }

        staffRepository.save(user);
        auditLogService.log("TOGGLE_STAFF_STATUS", (action.equals("Khóa") ? "khóa" : "mở khóa") + " tài khoản nhân viên: " + user.getFullName() + " (" + user.getUsername() + ").");
        return action; // Trả về để Controller dùng [cite: 2026-03-24]
    }

    @Override
    public StaffRequestDTO getStaffById(Long id) {
        User user = userRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy nhân viên!"));

        return staffMapper.toRequestDTO(user);
    }

    @Override
    public List<StaffProfile> findByRole(String roleName) {
        RoleType type = RoleType.valueOf(roleName.toUpperCase());
        return staffRepository.findByRoleType(type);
    }
}
