package org.megadiiiii.elms_api.services.impl;

import org.megadiiiii.elms_api.config.PasswordGenerator;
import org.megadiiiii.elms_api.constant.RoleType;
import org.megadiiiii.elms_api.constant.UserStatus;
import org.megadiiiii.elms_api.dto.request.StudentRequestDTO;
import org.megadiiiii.elms_api.dto.response.StudentDetailDTO;
import org.megadiiiii.elms_api.dto.response.StudentSummaryDTO;
import org.megadiiiii.elms_api.mappers.StudentMapper;
import org.megadiiiii.elms_api.models.Role;
import org.megadiiiii.elms_api.models.StudentProfile;
import org.megadiiiii.elms_api.models.User;
import org.megadiiiii.elms_api.repository.RoleRepository;
import org.megadiiiii.elms_api.repository.StudentRepository;
import org.megadiiiii.elms_api.repository.UserRepository;
import org.megadiiiii.elms_api.services.EmailService;
import org.megadiiiii.elms_api.services.StudentService;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDate;

@Service
@RequiredArgsConstructor
public class StudentServiceImpl implements StudentService {
    private final StudentRepository studentRepository;
    private final PasswordEncoder passwordEncoder;
    private final RoleRepository roleRepository;
    private final UserRepository userRepository;
    private final StudentMapper studentMapper;
    private final PasswordGenerator passwordGenerator;
    private final EmailService emailService;

    @Override
    public Page<StudentSummaryDTO> getAllStudentSummaries(int page, int size, String keyword) {
        Pageable pageable = PageRequest.of(page - 1, size);
        String searchKeyword = (keyword != null && !keyword.isBlank()) ? keyword : null;
        return studentRepository.searchStudents(searchKeyword, pageable);
    }

    @Override
    public StudentDetailDTO getStudentDetailById(Long id) {
        return studentRepository.findStudentDetailById(id)
                .orElseThrow(() -> new IllegalArgumentException("Học viên không tồn tại hoặc đã bị xóa!"));
    }

    @Override
    public String generateNextStudentCode() {
        String fullPrefix = RoleType.STUDENT.getPrefix() + "-" + LocalDate.now().getYear();
        String lastCode = studentRepository.findMaxStudentCode(fullPrefix);

        int nextNum = 1;
        if (lastCode != null && lastCode.startsWith(fullPrefix)) {
            try {
                String numberPart = lastCode.substring(fullPrefix.length());
                nextNum = Integer.parseInt(numberPart) + 1;
            } catch (Exception e) {
                nextNum = 1;
            }
        }
        return fullPrefix + String.format("%04d", nextNum);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void createStudent(StudentRequestDTO requestDTO) {
        if (userRepository.findByEmail(requestDTO.getEmail()).isPresent()) {
            throw new IllegalArgumentException("Email '" + requestDTO.getEmail() + "' đã được sử dụng bởi tài khoản khác!");
        }

        String autoGeneratedCode = generateNextStudentCode();
        String rawPassword = passwordGenerator.generateSecurePassword();

        User user = new User();
        user.setUsername(autoGeneratedCode);
        user.setEmail(requestDTO.getEmail());
        user.setPassword(passwordEncoder.encode(rawPassword));

        user.setFullName(requestDTO.getStudentName());
        user.setPhone(requestDTO.getPhone());
        user.setGender(requestDTO.getGender());
        user.setAddress(requestDTO.getAddress());
        user.setDob(requestDTO.getDob());
        user.setAvatar("default-avatar.png");
        user.setNationality(requestDTO.getNationality());

        Role role = roleRepository.findByName(RoleType.STUDENT)
                .orElseThrow(() -> new IllegalArgumentException("Vai trò STUDENT không tồn tại trong hệ thống!"));
        user.setRole(role);
        user.setStatus(UserStatus.ACTIVE);

        StudentProfile profile = new StudentProfile();
        profile.setStudentCode(autoGeneratedCode);
        profile.setStudentNickname(requestDTO.getStudentNickname());
        profile.setParentName(requestDTO.getParentName());
        profile.setParentPhone(requestDTO.getParentPhone());
        profile.setParentEmail(requestDTO.getParentEmail());
        profile.setUser(user);

        if (requestDTO.getAvatarUrl() != null && !requestDTO.getAvatarUrl().isBlank()) {
            user.setAvatar(requestDTO.getAvatarUrl());
        }

        user.setStudentProfile(profile);
        studentRepository.save(user); // Cascade saves the profile

        emailService.sendAccountInfo(user.getEmail(), user.getUsername(), rawPassword, role.getName().name());
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void updateStudent(Long id, StudentRequestDTO dto) {
        User user = studentRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Không tìm thấy học viên!"));

        if (!user.getEmail().equalsIgnoreCase(dto.getEmail())) {
            userRepository.findByEmail(dto.getEmail()).ifPresent(existingUser -> {
                if (!existingUser.getId().equals(user.getId())) {
                    throw new IllegalArgumentException("Email '" + dto.getEmail() + "' đã được sử dụng bởi tài khoản khác!");
                }
            });
        }

        String currentAvatar = user.getAvatar();

        studentMapper.updateEntityFromDTO(dto, user);

        if (dto.getAvatarUrl() != null && !dto.getAvatarUrl().isBlank()) {
            user.setAvatar(dto.getAvatarUrl());
            if (currentAvatar != null && !currentAvatar.equals(dto.getAvatarUrl()) && !currentAvatar.equals("default-avatar.png")) {
                try {
                    Files.deleteIfExists(Paths.get("./uploads/avatars").resolve(currentAvatar));
                } catch (IOException e) {
                    // Ignore error deleting file
                }
            }
        } else {
            user.setAvatar(currentAvatar);
        }

        studentRepository.save(user);
    }

    @Override
    public StudentRequestDTO getStudentRequestById(Long id) {
        User user = studentRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Không tìm thấy học viên!"));
        return studentMapper.toRequestDTO(user);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void resetPassword(Long id) {
        User user = studentRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Không tìm thấy học viên để reset mật khẩu!"));

        String newRawPassword = passwordGenerator.generateSecurePassword();
        user.setPassword(passwordEncoder.encode(newRawPassword));
        studentRepository.save(user);

        emailService.sendResetPassword(user.getEmail(), user.getUsername(), newRawPassword);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public String toggleStudentStatus(Long id) {
        User user = studentRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Không tìm thấy học viên để xử lý trạng thái!"));

        String action;
        if (user.getStatus() == UserStatus.ACTIVE) {
            user.setStatus(UserStatus.INACTIVE);
            action = "Khóa";
        } else {
            user.setStatus(UserStatus.ACTIVE);
            action = "Mở khóa";
        }

        studentRepository.save(user);
        return action;
    }

    @Override
    public java.util.List<StudentSummaryDTO> searchActiveStudentsForAutocomplete(String keyword) {
        String searchKeyword = (keyword != null && !keyword.isBlank()) ? keyword.trim() : null;
        org.springframework.data.domain.Pageable limitTen = org.springframework.data.domain.PageRequest.of(0, 10);
        return studentRepository.searchActiveStudentsForAutocomplete(searchKeyword, limitTen);
    }
}
